### ISSUE TITLE
Print PDF issue in the newer version

### ISSUE THREAD

**Issue by sanjayykm** [luis901101/zsdk#13]
Hi, 
Print PDF was working fine in 2.0.2+13 but now it is not working in the 3.2.0+2 version.
getting error as below
cause: NO_CONNECTION, Status: UNKNOWN,
errorCode: PRINTER_REBOOTED, message: Printer was rebooted to be able to use PDF Direct feature.

Note: I am using a Zebra ZD621 printer.

**Comment by luis901101** [comment]
Hi, since v3.1.0+1 the plugin supports PDF direct printing on both iOS and Android, before this version, the PDF printing was only available on Android, and it was by using some kind of workaround converting the PDF to image and printing it as image, which was not reliable and caused some issues depending on the ticket dimensions, etc. Now the PDF printing is the right way and according to the manufacturer, you just need to be sure your printing is using >= Link-OS v6.3 and you have installed the Virtual Device for PDF. 
For your printer you can check here for the firmware and software: https://www.zebra.com/es/es/support-downloads/printers/desktop/ZD621.html

**Comment by sanjayykm** [comment]
Hi @luis901101, Thank you for your quick response, 
I updated the Link-OS to the latest and can print PDFs directly from your library.
However, this doesn't work in release mode but works fine in debug mode.
Do you have any idea why?

**Comment by luis901101** [comment]
> Hi @luis901101, Thank you for your quick response, I updated the Link-OS to the latest and can print PDFs directly from your library. However, this doesn't work in release mode but works fine in debug mode. Do you have any idea why?

It should work in release mode as well, share any logs you have.

**Comment by sanjayykm** [comment]
I don't have much,
after calling print pdf method, I got future value which is below
ZPL Data status- Status.READY_TO_PRINT, errorCode: ErrorCode.SUCCESS, cause: Cause.UNKNOWN

**Comment by luis901101** [comment]
That is the expected response, without any further info I’m afraid I cant help you

**Comment by tomaspodmanicky** [comment]
After updating package from 2.x.x to the latest version all of our clients were not able to print (warehouses - a lot of printers). We tried with one of the clients to update firmware at their printer but nothing changed. This is just not good. I had to downgrade the package.

**Comment by tomaspodmanicky** [comment]
Is this function going to be supported in the future? `printPdfAsImageOverTCPIP`

**Comment by luis901101** [comment]
> After updating package from 2.x.x to the latest version all of our clients were not able to print (warehouses - a lot of printers). We tried with one of the clients to update firmware at their printer but nothing changed. This is just not good. I had to downgrade the package.

Hi @tomaspodmanicky ZPL printing remains the same in the latest version, the only change was regarding PDF printing which is now using PDF direct instead of a workaround converting the PDF to image. In a previous comment in this thread I mention the necessary steps to prepare the printer to use PDF direct print anyway as I see this is a recurrent issue I just updated the README.md with the necessary steps, please check it here: https://pub.dev/packages/zsdk#note

**Comment by luis901101** [comment]
> Is this function going to be supported in the future? `printPdfAsImageOverTCPIP`

I don't think so, as I mentioned before this was just a workaround to somehow support PDF printing as former versions of Link OS didn't support PDF printing at least not for free, the `printPdfAsImageOverTCPIP` uses a function to convert the PDF to image and this can cause issues with the document dimensions and sometimes 1D or 2D codes could be affected.
